'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { openDatabase } = require('../lib/db.js');
const { createUser } = require('../lib/user-store.js');
const { createClass } = require('../lib/class-store.js');
const { createSyntheticLesson } = require('../lib/synthetic-lesson.js');
const { applyAction, readState, sessionPayload } = require('../lib/class-session-store.js');

test('correction answers persist across database reopen, stage switches and reset; keys stay teacher-only', t => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'correction-session-'));
  const databasePath = path.join(directory, 'app.sqlite');
  let db = openDatabase(databasePath);
  t.after(() => { db.close(); fs.rmSync(directory, { recursive: true, force: true }); });
  const teacher = createUser({ email: 'correction@test.local', displayName: 'Teacher', passwordHash: 'unused' }, db);
  const content = createSyntheticLesson('Grammar', { template: 'template-2' });
  db.prepare("UPDATE library_lessons SET content_json = ?, is_available = 1, revision = 1 WHERE id = 'superhero'").run(JSON.stringify(content));
  const lesson = createClass({ name: 'Grammar', lessonId: 'superhero', expectedRevision: 1, requestKey: crypto.randomUUID() }, teacher.id, db);
  const access = { role: 'teacher', classId: lesson.id, ownerId: teacher.id }, student = { ...access, role: 'student' };
  let state = readState(lesson.id, db);
  const select = stageId => { state = applyAction(access, { type: 'select-stage', stageId, expectedVersion: state.version }, db); };
  const task = content.stages[5].content[5];
  const action = { type: 'type-answer', stageId: 'grammar-focus', componentId: task.id,
    itemId: task.items[0].id, value: task.items[0].answers[0] };
  assert.throws(() => applyAction(student, { ...action, expectedVersion: state.version }, db), { statusCode: 409 });
  select('grammar-focus');
  assert.throws(() => applyAction(access, { ...action, expectedVersion: state.version }, db), { statusCode: 403 });
  state = applyAction(student, { ...action, expectedVersion: state.version }, db);
  assert.equal(state.exercises[task.id].answers[action.itemId].status, 'correct');
  assert.throws(() => applyAction(student, { ...action, expectedVersion: state.version - 1 }, db), { statusCode: 409 });
  select('warm-up'); select('grammar-focus');
  db.close(); db = openDatabase(databasePath);
  assert.deepEqual(readState(lesson.id, db), state);
  const studentPayload = sessionPayload(student, db), teacherPayload = sessionPayload(access, db);
  assert.deepEqual(studentPayload.state.exercises, teacherPayload.state.exercises);
  const studentContent = studentPayload.lesson.content.stages[5].content;
  assert.equal(studentContent.some(item => item.id === `${task.id}-answer-key`), false);
  assert.equal(teacherPayload.lesson.content.stages[5].content.some(item => item.id === `${task.id}-answer-key`), true);
  state = applyAction(access, { type: 'reset-stage', stageId: 'grammar-focus', expectedVersion: state.version }, db);
  assert.equal(state.exercises[task.id], undefined);
  assert.equal(readState(lesson.id, db).exercises[task.id], undefined);
});
