'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const crypto = require('node:crypto');
const { spawn, spawnSync } = require('node:child_process');
const { once } = require('node:events');
const { WebSocket } = require('ws');
const { openDatabase } = require('../lib/db.js');
const { createUser } = require('../lib/user-store.js');
const { createSession } = require('../lib/session-store.js');
const { createLessonDraft, completeLessonDraft, findLessonDraft } = require('../lib/lesson-draft-store.js');
const { publishLesson, findLibraryLesson } = require('../lib/library-store.js');
const { createClass } = require('../lib/class-store.js');

test('video upload, immutable publication, range access and class media signals', { timeout: 20000 }, async t => {
  if (spawnSync(process.env.FFPROBE_PATH || 'ffprobe', ['-version']).status !== 0) { t.skip('ffprobe is required for video upload integration'); return; }
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'teach-video-'));
  const dbPath = path.join(directory, 'app.sqlite'), assets = path.join(directory, 'assets');
  const db = openDatabase(dbPath);
  const admin = createUser({ email: 'video@test.local', displayName: 'Video', role: 'admin', passwordHash: 'unused' }, db);
  const cookie = `teach_session=${createSession(admin.id, db).token}`;
  const other = createUser({ email: 'other@test.local', displayName: 'Other', role: 'admin', passwordHash: 'unused' }, db);
  const otherCookie = `teach_session=${createSession(other.id, db).token}`;
  const created = createLessonDraft({ ownerAdminId: admin.id, topic: 'Watch', template: 'template-2' }, db);
  completeLessonDraft(created.id, admin.id, { meta: { title: 'Watch' }, stages: [{ id: 'watch-and-interact', title: 'Watch', content: [{ type: 'videoPlayer', id: 'watch-video', title: 'Watch' }] }] }, db);
  const server = spawn(process.execPath, ['server.js'], { cwd: path.join(__dirname, '..'), env: { ...process.env, APP_DB_PATH: dbPath, DRAFT_ASSETS_DIR: assets, HOST: '127.0.0.1', PORT: String(31000 + Math.floor(Math.random() * 10000)) }, stdio: ['ignore', 'pipe', 'pipe'] });
  const sockets = [];
  t.after(async () => { sockets.forEach(s => s.terminate()); if (server.exitCode === null) { const done = once(server, 'exit'); server.kill(); await done; } db.close(); fs.rmSync(directory, { recursive: true, force: true }); });
  let output = '';
  const base = await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error(output)), 5000);
    server.stdout.on('data', data => { output += data; const match = output.match(/http:\/\/127\.0\.0\.1:(\d+)/); if (match) { clearTimeout(timer); resolve(match[0]); } });
    server.stderr.on('data', data => { output += data; });
  });
  const request = (url, opts = {}, auth = cookie) => fetch(base + url, { ...opts, headers: { Cookie: auth, ...opts.headers } });
  const route = `/api/lesson-drafts/${created.id}/video-player/watch-video/video`;
  const bytes = fs.readFileSync(path.join(__dirname, 'fixtures/watch-video.mp4'));
  assert.equal((await request(route, { method: 'PUT', body: bytes }, otherCookie)).status, 404);
  assert.equal((await request(route, { method: 'PUT', body: 'not an MP4' })).status, 415);
  const uploaded = await request(route, { method: 'PUT', body: bytes });
  assert.equal(uploaded.status, 200, await uploaded.clone().text());
  let draft = (await uploaded.json()).draft;
  const question = { id: 'q-1', atMs: 100, mode: 'multiple', text: 'What did you see?', options: [
    { id: 'a', text: 'First' }, { id: 'b', text: 'Second' }, { id: 'c', text: 'Third' },
  ], correctOptionIds: ['a', 'c'] };
  const questionRoute = route.replace(/video$/, 'questions');
  const saveQuestions = (questions, auth = cookie, expectedVideoSrc = draft.content.stages[0].content[0].videoSrc) => request(questionRoute, {
    method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ questions, expectedVideoSrc }),
  }, auth);
  assert.ok(draft.content.stages[0].content[0].durationMs > 100);
  assert.equal((await saveQuestions([question], otherCookie)).status, 404);
  assert.equal((await saveQuestions([{ ...question, atMs: 999999 }])).status, 400);
  assert.equal((await saveQuestions([{ ...question, correctOptionIds: ['unknown'] }])).status, 400);
  assert.equal((await saveQuestions([question], cookie, '/old-video.mp4')).status, 409);
  const savedQuestions = await saveQuestions([question]);
  assert.equal(savedQuestions.status, 200);
  draft = (await savedQuestions.json()).draft;
  assert.deepEqual(draft.content.stages[0].content[0].questions, [question]);
  const source = draft.content.stages[0].content[0].videoSrc;
  const range = await request(source, { headers: { Range: 'bytes=0-15' } });
  assert.equal(range.status, 206); assert.deepEqual(Buffer.from(await range.arrayBuffer()), bytes.subarray(0, 16));
  const input = { expectedRevision: 0, expectedUpdatedAt: draft.updatedAt, title: 'Watch lesson', description: 'Video lesson', category: 'Speaking', duration: '10 мин', skills: ['Speaking'], coverUpload: { type: 'image/png', data: fs.readFileSync(path.join(__dirname, '../assets/images/lesson-travel.png')).toString('base64') } };
  const publication = publishLesson(draft.id, admin.id, input, db, assets);
  const published = findLibraryLesson(publication.id, db).content.stages[0].content[0].videoSrc;
  assert.equal((await request(published, { method: 'HEAD' })).headers.get('content-length'), String(bytes.length));
  const classroom = createClass({ name: 'Video class', lessonId: publication.id, expectedRevision: 1, requestKey: crypto.randomUUID() }, admin.id, db);
  assert.deepEqual(classroom.content.stages[0].content[0].questions, [question]);
  const classSource = classroom.content.stages[0].content[0].videoSrc;
  const joined = await request(classroom.invitePath, { redirect: 'manual' }, '');
  const guest = joined.headers.get('set-cookie').split(';')[0];
  assert.equal((await request(classSource, {}, '')).status, 401);
  assert.equal((await request(classSource, {}, otherCookie)).status, 404);
  assert.equal((await request(classSource, { headers: { Range: 'bytes=-10' } }, guest)).status, 206);
  assert.equal((await request(classSource, { headers: { Range: 'bytes=999999-' } }, guest)).status, 416);
  assert.equal((await request(route, { method: 'DELETE' })).status, 200);
  assert.equal((await request(source)).status, 404);
  assert.deepEqual(Buffer.from(await (await request(classSource, {}, guest)).arrayBuffer()), bytes);
  assert.equal(findLessonDraft(draft.id, admin.id, db).content.stages[0].content[0].videoSrc, undefined);
  assert.deepEqual(findLessonDraft(draft.id, admin.id, db).content.stages[0].content[0].questions, []);
  function connect(role, auth) {
    const ws = new WebSocket(`${base.replace('http:', 'ws:')}/ws/classes/${classroom.id}?role=${role}`, { headers: { Cookie: auth, Origin: base } }); sockets.push(ws);
    const queue = [], waiters = [];
    ws.on('message', raw => { const message = JSON.parse(raw); const index = waiters.findIndex(w => w.type === message.type); if (index < 0) queue.push(message); else { const [w] = waiters.splice(index, 1); clearTimeout(w.timer); w.resolve(message); } });
    ws.next = type => { const index = queue.findIndex(m => m.type === type); if (index >= 0) return Promise.resolve(queue.splice(index, 1)[0]); return new Promise((resolve, reject) => { waiters.push({ type, resolve, timer: setTimeout(() => reject(new Error(`Missing ${type}`)), 2000) }); }); };
    return ws;
  }
  const teacher = connect('teacher', cookie), student = connect('student', guest);
  await Promise.all([teacher.next('snapshot'), student.next('snapshot')]);
  const baseAction = { stageId: 'watch-and-interact', componentId: 'watch-video' };
  student.send(JSON.stringify({ ...baseAction, type: 'media-command', action: 'play', position: 50 }));
  const [a, b] = await Promise.all([teacher.next('media-command'), student.next('media-command')]);
  assert.deepEqual(a, b); assert.equal(a.action, 'play'); assert.equal('position' in a, false);
  teacher.send(JSON.stringify({ ...baseAction, type: 'media-command', action: 'pause' }));
  assert.equal((await student.next('media-command')).action, 'pause'); await teacher.next('media-command');
  student.send(JSON.stringify({ ...baseAction, type: 'media-align', position: 20 }));
  assert.ok((await student.next('media-error')).error);
  teacher.send(JSON.stringify({ ...baseAction, type: 'media-align', position: 0.5 }));
  assert.equal((await student.next('media-align')).position, 0.5);
  student.send(JSON.stringify({ ...baseAction, type: 'media-status', position: 0.4, paused: true, buffering: false, blocked: false }));
  assert.equal((await teacher.next('media-status')).position, 0.4);
  student.send(JSON.stringify({ ...baseAction, type: 'video-question-answer', questionId: question.id, selectedOptionIds: ['b'], expectedVersion: 0 }));
  const [teacherAnswer, studentAnswer] = await Promise.all([teacher.next('action'), student.next('action')]);
  assert.deepEqual(teacherAnswer.state.videoQuestions, studentAnswer.state.videoQuestions);
  assert.deepEqual(teacherAnswer.state.videoQuestions['watch-video']['q-1'], { selectedOptionIds: ['b'], correct: false, answeredBy: 'student' });
  teacher.send(JSON.stringify({ ...baseAction, type: 'video-question-answer', questionId: question.id, selectedOptionIds: ['a', 'c'], expectedVersion: 0 }));
  assert.deepEqual((await teacher.next('action-error')).state.videoQuestions, teacherAnswer.state.videoQuestions);
  const reconnected = connect('student', guest);
  const restored = await reconnected.next('snapshot');
  assert.deepEqual(restored.state.videoQuestions, teacherAnswer.state.videoQuestions);
  teacher.send(JSON.stringify({ ...baseAction, type: 'reset-stage', expectedVersion: restored.state.version }));
  const reset = await teacher.next('action'); await reconnected.next('action');
  assert.deepEqual(reset.state.videoQuestions, {});
  assert.equal(reset.state.videoQuestionEpochs['watch-video'], 1);
  reconnected.send(JSON.stringify({ ...baseAction, type: 'video-question-answer', questionId: question.id, selectedOptionIds: ['unknown'], expectedVersion: reset.state.version }));
  assert.ok((await reconnected.next('action-error')).error);
  reconnected.send(JSON.stringify({ ...baseAction, type: 'video-question-answer', questionId: question.id, selectedOptionIds: ['c', 'a'], expectedVersion: reset.state.version }));
  const correct = await teacher.next('action'); await reconnected.next('action');
  assert.equal(correct.state.videoQuestions['watch-video']['q-1'].correct, true);

});
